### ISSUE TITLE
australia-bom broken after last commit?

### ISSUE THREAD

**Issue by dcava** [sprinkler/rainmachine-developer-resources#24]
Hi @ascl00

I've been using the Australia BOM parser in Brisbane QLD for a while with no problems, but since the last commit #22 I get this error:

```
2020-08-26 22:32:27,280 - WARNING - user-australia-bom:1278 - Failed to convert - into a float
2020-08-26 22:32:27,288 - WARNING - user-australia-bom:1278 - Failed to convert - into a float
2020-08-26 22:32:27,298 - ERROR - rmParserManager:168 -   * Cannot execute parser Australia BoM
2020-08-26 22:32:27,307 - ERROR - rmParserManager:169 - unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "./RMParserFramework/rmParserManager.py", line 165, in run
  File "./RMParserFramework/rmParser.py", line 49, in timedPerform
  File "/rainmachine-app/RMParserFramework/parsers/user-australia-bom.py", line 1262, in perform
    self.__getObservationData(self.params["State"])
  File "/rainmachine-app/RMParserFramework/parsers/user-australia-bom.py", line 1145, in __getObservationData
    self.__parseJSONObservationData(data)
  File "/rainmachine-app/RMParserFramework/parsers/user-australia-bom.py", line 1112, in __parseJSONObservationData
    debug_str=self.__parseObservationValue(key, value, timestamp, debug_str)
  File "/rainmachine-app/RMParserFramework/parsers/user-australia-bom.py", line 1059, in __parseObservationValue
    value = (self.__toFloat(value) + old_value)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

Which I'm guessing is a problem with "old_value" in the RAIN parser being "NoneType"?

Commenting out lines 1056-59:
```
            # # NOTE: We SUM these two values to get the total for the 60 minute period.
            # old_value = self.__getValue(RMParser.dataType.RAIN, timestamp)
            # if old_value is not None:
            #value = (self.__toFloat(value) + old_value)
```
Will get things working partially working, but obviously defeats the purpose of the changes, and seems to break a few other things.

Any one else seeing this? Could it be location specific for Brisbane.QLD?

David

**Comment by ascl00** [comment]
Hi David,

Well that's crappy, sorry about that. The fix should be simple tho, note 
the code you commented out has:

if old_value is not None:

It sounds like it should be

if old_value is not None and old_value is not NoneType:

The old_value/value thing is supposed to deal with a 30 minute update 
cadence of BOM vs 60 minute in rainmeter. It is possible QLD doesn't use 
a 30 minute cadence. I will check it out later today and see if I can 
provide a fix. In the mean time the above might work for you.

Cheers

Nick

**Comment by ascl00** [comment]
Can you please let me know which observatory you are getting results from? debug logs would be great but not required if I can reproduce.

Using:

> 2020-08-28 13:27:39,440 - DEBUG - australia-bom:860 - Found closest observatory (27.5586208624 km) AMBERLEY AMO 
> 2020-08-28 13:27:39,440 - DEBUG - australia-bom:1129 - Got a URL of http://www.bom.gov.au/fwo/IDQ60801/IDQ60801.94568.json
> 2020-08-28 13:27:39,440 - DEBUG - rmParser:115 - Parser 'Australia BoM': downloading from http://www.bom.gov.au/fwo/IDQ60801/IDQ60801.94568.json

I do not see a problem.

**Comment by ascl00** [comment]
Ah, I see how there could be a potential problem here. It isn't old_value that is None, it is the return from __toFloat(). Okay, that's fixable.... I'd love to see the input data for it tho, it shouldn't happen, but perhaps there was something odd in the file or some corruption or something.
EDIT: it is right there in the log:
 - WARNING - user-australia-bom:1278 - Failed to convert - into a float

**Comment by ascl00** [comment]
PR created that should resolve this. Thanks for the bug report!

**Comment by dcava** [comment]
THanks @ascl00 !!
